services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-mydb}'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - base_repo_db_local_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
    volumes:
      - base_repo_redis_local_volume:/data

    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD:-password}', '--appendonly', 'yes'] # enables persistence

volumes:
  base_repo_db_local_volume:
  base_repo_redis_local_volume:
